INSERT INTO kereta (id, namka,stasiun) VALUES ('3', 'MALABAR','MALANG MADIUN YOGYAKARTA PURWOKERTO BANDUNG');
INSERT INTO kereta (id, namka,stasiun) VALUES ('4', 'ARGO BROMO','SURABAYA SEMARANG CIREBON JAKARTA');
INSERT INTO kereta (id, namka,stasiun) VALUES ('5', 'SERAYU','PURWOKERTO CIREBON JAKARTA');
INSERT INTO kereta (id, namka,stasiun) VALUES ('6', 'SEMBRANI','JAKARTA CIREBON SEMARANG SURABAYA');
INSERT INTO kereta (id, namka,stasiun) VALUES ('7', 'SENJA UTAMA SOLO','SURAKARTA YOGYAKARTA PURWOKERTO CIREBON JAKARTA');
INSERT INTO kereta (id, namka,stasiun) VALUES ('8', 'ARGO PARAHYANGAN','BANDUNG JAKARTA');
INSERT INTO kereta (id, namka,stasiun) VALUES ('9', 'JOGLOSEMARKERTO','PURWOKERTO YOGYAKARTA SURAKARTA SEMARANG');
INSERT INTO kereta (id, namka,stasiun) VALUES ('10', 'ARGO JATI','JAKARTA CIREBON');